{% set pyproject = load_file_data('pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project') %}
{% set homepage = project.get('urls').get('Homepage') %}
{% set version = project.get('version')%}
{% set name = project.get('name') %}
{% set license_files = pyproject.get('tool').get('setuptools').get('license-files') %}
{% set description = project.get('description') %}
{% set license = project.get('license').get('text') %}
{% set python = project.get('requires-python') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - pip
    - python {{ python }}
  host:
    - python {{ python }}
  run:
    - python {{ python }}

test:
  source_files:
    - beerpy.py
    - example.py

  commands:
    - python example.py --local

about:
  home: https://srebughini.github.io/ASALI/
  summary: {{ description }}
  license: {{ license }}
  license_file: {{ license_files[0] }}
  dev_url: {{ homepage }}
  description: {{ description }}
  doc_url: {{ homepage }}

extra:
  recipe-maintainers:
    - srebughini
