{% set data = load_setup_py_data() %}

package:
  name: "beerpy"
  version: {{ data.get('version') }}

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - pip
    - python {{ python }}
  host:
    - python {{ python }}
  run:
    - python {{ python }}

test:
  imports:
    - beerpy

  source_files:
    - tests
    - run_tests.py

  commands:
    - python run_tests.py --local

about:
  home: https://srebughini.github.io/BEERQ/
  summary: "A Python library to randomly generate beer quotes"
  license: GPL
  license_family: GPL
  license_file: LICENSE
  dev_url: https://github.com/srebughini/BEERPY
  description: A Python library to randomly generate beer quotes
  doc_url: https://github.com/srebughini/BEERPY/blob/main/README.md

extra:
  recipe-maintainers:
    - srebughini